cicd:
- changed-files:
  - any-glob-to-any-file:
    - .github/**

terraform:
- changed-files:
  - any-glob-to-any-file:
    - src/**

docs:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.md'
